//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_System.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Mst_Project = new HashSet<Mst_Project>();
            this.Mst_Project1 = new HashSet<Mst_Project>();
            this.Mst_Project_Documents = new HashSet<Mst_Project_Documents>();
            this.Mst_ProjectUsers = new HashSet<Mst_ProjectUsers>();
            this.Mst_Task = new HashSet<Mst_Task>();
            this.Mst_Task1 = new HashSet<Mst_Task>();
            this.Mst_Project2 = new HashSet<Mst_Project>();
            this.Mst_Project3 = new HashSet<Mst_Project>();
            this.Mst_Task2 = new HashSet<Mst_Task>();
            this.Mst_Task3 = new HashSet<Mst_Task>();
            this.Trans_Ticket = new HashSet<Trans_Ticket>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Mst_Project> Mst_Project { get; set; }
        public virtual ICollection<Mst_Project> Mst_Project1 { get; set; }
        public virtual ICollection<Mst_Project_Documents> Mst_Project_Documents { get; set; }
        public virtual ICollection<Mst_ProjectUsers> Mst_ProjectUsers { get; set; }
        public virtual ICollection<Mst_Task> Mst_Task { get; set; }
        public virtual ICollection<Mst_Task> Mst_Task1 { get; set; }
        public virtual ICollection<Mst_Project> Mst_Project2 { get; set; }
        public virtual ICollection<Mst_Project> Mst_Project3 { get; set; }
        public virtual ICollection<Mst_Task> Mst_Task2 { get; set; }
        public virtual ICollection<Mst_Task> Mst_Task3 { get; set; }
        public virtual ICollection<Trans_Ticket> Trans_Ticket { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
