//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_System.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Task
    {
        public Mst_Task()
        {
            this.Trans_Ticket = new HashSet<Trans_Ticket>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string TaskDisplayName { get; set; }
        public int ProjectID { get; set; }
        public string AssignedTo { get; set; }
        public string RefereedTo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> AssigndedDate { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> Task_Status { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Attachment1_Name { get; set; }
        public string Attachment1_Path { get; set; }
        public string Attachment2_Name { get; set; }
        public string Attachment2_Path { get; set; }
        public string Attachment3_Name { get; set; }
        public string Attachment3_Path { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual Mst_Project Mst_Project { get; set; }
        public virtual Mst_TaskStatus Mst_TaskStatus { get; set; }
        public virtual Mst_TaskPriority Mst_TaskPriority { get; set; }
        public virtual Mst_TaskType Mst_TaskType { get; set; }
        public virtual ICollection<Trans_Ticket> Trans_Ticket { get; set; }
    }
}
