//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_System.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_TaskPriority
    {
        public Mst_TaskPriority()
        {
            this.Mst_Task = new HashSet<Mst_Task>();
        }
    
        public int ID { get; set; }
        public string PriorityName { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Mst_Task> Mst_Task { get; set; }
    }
}
