//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_System.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Project
    {
        public Mst_Project()
        {
            this.Mst_Project_Documents = new HashSet<Mst_Project_Documents>();
            this.Mst_ProjectUsers = new HashSet<Mst_ProjectUsers>();
            this.Mst_Task = new HashSet<Mst_Task>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ClientID { get; set; }
        public string PManagerID { get; set; }
        public Nullable<System.DateTime> SignUpDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> ProposedEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ShortName { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<Mst_Project_Documents> Mst_Project_Documents { get; set; }
        public virtual ICollection<Mst_ProjectUsers> Mst_ProjectUsers { get; set; }
        public virtual ICollection<Mst_Task> Mst_Task { get; set; }
    }
}
