//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_System.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Ticket
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string DisplayName { get; set; }
        public string Comments { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentPath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string O_Title { get; set; }
        public string N_Title { get; set; }
        public string O_Description { get; set; }
        public string N_Description { get; set; }
        public string O_AssignedTo { get; set; }
        public string N_AssignedTo { get; set; }
        public string O_RefereedTo { get; set; }
        public string N_RefereedTo { get; set; }
        public Nullable<int> O_PriorityID { get; set; }
        public Nullable<int> N_PriorityID { get; set; }
        public Nullable<int> O_TypeID { get; set; }
        public Nullable<int> N_TypeID { get; set; }
        public Nullable<int> O_Task_Status { get; set; }
        public Nullable<int> N_Task_Statuus { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Mst_Task Mst_Task { get; set; }
    }
}
